# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Goppuku < Formula
  desc "Have a VM put itself down if a given condition is met
"
  homepage "https://github.com/jlucktay/goppuku"
  version "0.6.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jlucktay/goppuku/releases/download/v0.6.6/goppuku_0.6.6_Darwin_x86_64.tar.gz"
      sha256 "5fd2ef8a0e4b80280e3baef5a10f298e223d3908eda054a4e848d4fd715770cc"

      def install
        bin.install "goppuku"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jlucktay/goppuku/releases/download/v0.6.6/goppuku_0.6.6_Darwin_arm64.tar.gz"
      sha256 "969d82b1a1fb887d7469b017af855a0d0028ffb7c94b67ae3b0c3bbd77c56424"

      def install
        bin.install "goppuku"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jlucktay/goppuku/releases/download/v0.6.6/goppuku_0.6.6_Linux_arm64.tar.gz"
      sha256 "6ad9badd96c36a32a3b68b7a9f3f8463b4cf466b4628f9916fc017d946f10359"

      def install
        bin.install "goppuku"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jlucktay/goppuku/releases/download/v0.6.6/goppuku_0.6.6_Linux_x86_64.tar.gz"
      sha256 "eb5380018fb9c26b54fc77ef234a0ea7a17f8d99fc1ff97315c8db00f3e63461"

      def install
        bin.install "goppuku"
      end
    end
  end

  def caveats
    <<~EOS
      Please see the README for usage instructions:
      https://github.com/jlucktay/goppuku/blob/main/README.md
    EOS
  end

  test do
    system "#{bin}/goppuku"
  end
end
