# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Goppuku < Formula
  desc "Have a VM put itself down if a given condition is met
"
  homepage "https://github.com/jlucktay/goppuku"
  version "0.6.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jlucktay/goppuku/releases/download/v0.6.5/goppuku_0.6.5_Darwin_x86_64.tar.gz"
      sha256 "53053d32ac17b91e45402619cd9f514db56ae8deb029bf7c78bc67bfc508fd4c"

      def install
        bin.install "goppuku"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jlucktay/goppuku/releases/download/v0.6.5/goppuku_0.6.5_Darwin_arm64.tar.gz"
      sha256 "e562af2403a53a710e67a7f8a9aacd262d8dca2a5661b751f3de0ab2e43e2a6b"

      def install
        bin.install "goppuku"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jlucktay/goppuku/releases/download/v0.6.5/goppuku_0.6.5_Linux_arm64.tar.gz"
      sha256 "ba4cf7126b02706bd3ba57c30d090683e54f6f0afac569cbbc789711a22a96f9"

      def install
        bin.install "goppuku"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jlucktay/goppuku/releases/download/v0.6.5/goppuku_0.6.5_Linux_x86_64.tar.gz"
      sha256 "654183fce99486116d068ec461503144e689a64cc66b10f8519570871d86a461"

      def install
        bin.install "goppuku"
      end
    end
  end

  def caveats
    <<~EOS
      Please see the README for usage instructions:
      https://github.com/jlucktay/goppuku/blob/main/README.md
    EOS
  end

  test do
    system "#{bin}/goppuku"
  end
end
