# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MyGithubRepos < Formula
  desc "GraphQL-based tool to fetch GitHub repos sorted by creation date
"
  homepage "https://github.com/jlucktay/my-github-repos"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/jlucktay/my-github-repos/releases/download/v0.3.0/my-github-repos_0.3.0_Darwin_arm64.tar.gz"
      sha256 "fed2a10c41222bb1168100ae41682fc9a45b848353c30560ff06a68c9341283b"

      def install
        bin.install "my-github-repos"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jlucktay/my-github-repos/releases/download/v0.3.0/my-github-repos_0.3.0_Darwin_x86_64.tar.gz"
      sha256 "040852046bb3499966fe99a6d28d46ff1b064f94d26f0dfae1ec5f374cbcc8cd"

      def install
        bin.install "my-github-repos"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/jlucktay/my-github-repos/releases/download/v0.3.0/my-github-repos_0.3.0_Linux_x86_64.tar.gz"
      sha256 "fe618d56a5fb9cb95ed2f59d86253f74839dafcc9cac9d701504bc033d056859"

      def install
        bin.install "my-github-repos"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jlucktay/my-github-repos/releases/download/v0.3.0/my-github-repos_0.3.0_Linux_arm64.tar.gz"
      sha256 "f7bdce8a17838264039cb3150c1b3237d1b595959a8bd8ff87417eb1a04ce752"

      def install
        bin.install "my-github-repos"
      end
    end
  end

  def caveats; <<~EOS
    Please see the README for usage instructions:
    https://github.com/jlucktay/my-github-repos/blob/main/README.md
  EOS
  end

  test do
    system "#{bin}/my-github-repos --version"
  end
end
