# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MyGithubRepos < Formula
  desc "GraphQL-based tool to fetch GitHub repos sorted by creation date"
  homepage "https://github.com/jlucktay/my-github-repos"
  version "0.3.12"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jlucktay/my-github-repos/releases/download/v0.3.12/my-github-repos_Darwin_x86_64.tar.gz"
      sha256 "82be72dde8ea4cf2248f0d6d4fdf8ba23fdc36dc662e53ddaa09e18e0dfa491b"

      def install
        bin.install "my-github-repos"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jlucktay/my-github-repos/releases/download/v0.3.12/my-github-repos_Darwin_arm64.tar.gz"
      sha256 "9309d2b1d0930698a5aa649ab357dc4b11ebe44545cbb7285367ac98786ef813"

      def install
        bin.install "my-github-repos"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jlucktay/my-github-repos/releases/download/v0.3.12/my-github-repos_Linux_x86_64.tar.gz"
        sha256 "039ea5413d1f7866a5b73f8409c280e198c2745c42a8e9d4d29b80ca2af9fc6e"

        def install
          bin.install "my-github-repos"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jlucktay/my-github-repos/releases/download/v0.3.12/my-github-repos_Linux_arm64.tar.gz"
        sha256 "1898983cb6fa301e39de1ecbe9e52a2cb4405de803c107d84cf85cfda0af223b"

        def install
          bin.install "my-github-repos"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Please see the README for usage instructions:
      https://github.com/jlucktay/my-github-repos/blob/main/README.md
    EOS
  end

  test do
    system "#{bin}/my-github-repos --version"
  end
end
