# This file was generated by GoReleaser. DO NOT EDIT.
class Stack < Formula
  desc "A support tool for use with Terraform stacks, Azure DevOps build pipelines, and GitHub projects/repos."
  homepage "https://github.com/jlucktay/stack"
  version "0.5.6"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/jlucktay/stack/releases/download/v0.5.6/stack_0.5.6_Darwin_x86_64.tar.gz"
    sha256 "2d83d87191c88de4c03dde049ec1014b6b26a3d5a7cd512f6da5f48560cb5f77"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/jlucktay/stack/releases/download/v0.5.6/stack_0.5.6_Linux_x86_64.tar.gz"
      sha256 "2f47f612eea3f744ed41313d7ce690e6b145aa486c4b2bfbaa49569698b4e8fd"
    end
  end

  def install
    bin.install "stack"
  end

  def caveats; <<~EOS
    Please see the README for usage instructions: https://github.com/jlucktay/stack/blob/master/README.md
  EOS
  end
end
